name: Docs

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "apt-get update -y && apt-get install -y doxygen && pip3 install breathe spinx-rtd-theme"
          docs-folder: "doc/"

      - name: Override Jekyll
        run: touch doc/_build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs/_build/html
          branch: main
          repository-name: jdv52/libtest-docs
          target-folder: lib
