name: Docs

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: "doc"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Sphinx & Dependencies
        run: |
          sudo apt-get install python3-sphinx
          sudo apt-get install python3-breathe
          sudo apt-get install python3-sphinx-rtd-theme
          cd doc
          make html

      - name: Override Jekyll
        run: touch doc/_build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: doc/_build/html
          branch: main
          repository-name: jdv52/libtest-docs
          target-folder: lib
