name: Docs

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: "doc"

      - name: Build HTML
        run: sudo apt-get update &&
          sudo apt-get upgrade -y &&
          sudo apt-get install python3 python3-pip python3-venv &&
          python3 -m venv ./tmp &&
          source tmp/bin/activate &&
          pip3 install breathe sphinx-rtd-theme sphinx-doc

      - name: Override Jekyll
        run: touch doc/_build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs/_build/html
          branch: main
          repository-name: jdv52/libtest-docs
          target-folder: lib
