name: Docs

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: "doc"

      - name: Build HTML
        run: pyvenv install 3.6.8 &&
          pyvenv local 3.6.9 &&
          pip3 install breathe sphinx-rtd-theme sphinx &&
          cd doc &&
          sudo make html

      - name: Override Jekyll
        run: touch doc/_build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs/_build/html
          branch: main
          repository-name: jdv52/libtest-docs
          target-folder: lib
